### ISSUE TITLE
Found CSS Bug

### ISSUE THREAD

**Issue by marcovirtual** [kasparsd/contact-form-7-extras#15]
I use Contact Form 7 Controls and believe that I have found a bug with it.

In a form that has checkboxes, I like to have each checkbox option in a different line. To do this, I add the following CSS:

`span.wpcf7-list-item { display: block; } `

(This is the CSS recommended by the author of Contact Form 7 himself)

Well, when I activate Contact Form 7 controls, that CSS code simply stops working, and my checkbox options are displayed horizontally. If I deactivate it, everything comes back to normal.

**Comment by kasparsd** [comment]
Thanks for reporting the issue @marcovirtual! Could you please add some screenshots that would illustrate the issue before and after activating the plugin?

**Comment by marcovirtual** [comment]
Yes! 

Here are two screenshots to illustrate the problem:

This is what my form looks like when I have **just Contact Form 7 installed**,
 together with the piece of CSS code that I posted above, which puts each checkbox option in a new line:
 [https://i.imgur.com/WxnRC7m.png](url)

And this is what my form looks like **when I also activate Contact Form 7 Controls**.
 It is as if it ignored my custom CSS code. [https://i.imgur.com/SMa2qeu.png](url)

**Comment by kasparsd** [comment]
@marcovirtual This is very interesting. The CF7 Controls plugin includes CSS only for the admin area of the plugin.

Where did you put the CSS for the checkboxes? 

Maybe you have the "Disable default CSS for this form" selected?

![screenshot-1](https://user-images.githubusercontent.com/169055/32517212-66e2fe92-c40e-11e7-84c7-e2441ec0e0c6.png)

**Comment by marcovirtual** [comment]
Thanks for your feedback.

I put the CSS code in the "Additional CSS" option inside Appearance > Customize.

And no, I do not have the "Disable default CSS" option enabled.

**Comment by kasparsd** [comment]
Just confirmed the issue on this [demo page](https://demo.preseto.com/cf7-storage/cf7-extras/form-checkbox-css). This is caused by this logic required for disabling the front-end CSS:

https://github.com/kasparsd/contact-form-7-extras/blob/7fc217af292daf0fade58e9a3791ee38ad58b6e1/src/class-cf7-extras.php#L84-L85

The solution for now is to use stricter CSS rules to ensure they override the default Contact Form 7 styles:

```css
form span.wpcf7-list-item { display: block; }
```

Unfortunately, there is no way to disable the default Contact Form 7 CSS without waiting for the forms to render.
